require('config')
require('keybindings')
require('packages')
require('lualine-nvim')
require('lspsaga_config')
require('lsp_config')
require('filetree')
require('treesitter')
require('telescope_config')
require('trouble_config')
require('terminal')
require('gitsigns_config')
require('autopairs_config')
require('bufferline_config')
require('cmp_config')
require('null-ls_config')
require('comment_config')
require('colorizer_config')
require('highlight-text')
require('noice_config')
require('fidget_config')
require('alpha_config')
-- vim.opt.foldmethod = "expr"
-- vim.opt.foldexpr = "nvim_treesitter#foldexpr()"

