#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV 

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true 
bspc config gapless_monocle      true

# colors
# bspc config focused_border_color "#F0C674"
# bspc config focused_border_color "#89b4fa"
bspc config focused_border_color "#f38ba8"
bspc config focus_follows_pointer true

# rules for applications to be spawned on specific desktops
bspc rule -a Gimp desktop='^3' state=floating follow=on
# bspc rule -a firefox desktop='^1'
# bspc rule -a chromium desktop='^1'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
# bspc rule -a Alacritty desktop='^2' 
bspc rule -a FloatTerm state=floating 
# bspc rule -a Thunar state=floating 

