# import = ["/home/dev-737/.config/alacritty/themes/one_dark.toml"]
import = ["/home/dev-737/.config/alacritty/themes/nord.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 15.5

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[scrolling]
history = 1000
multiplier = 3

[window.padding]
x = 8
y = 2
